### ISSUE TITLE
Catboost doesn't support multiple eval sets (AutoTrees)

### ISSUE THREAD

**Issue by kgrushin** [Vasily-Sizov/autobinary_framework#1]
Добрый день! 

При запуске обучения `AutoTrees` методом `.model_fit_cv()` с использованием `catboost` на `GPU` выдает ошибку.
`CatBoostError: Multiple eval sets are not supported on GPU`

Из-за невозможности смены состояния и параметров обучения до начала работы метода `.model_fit_cv()` после их изменения в строках 617-624 (`trees/auto_trees.py`) для апдейта необходимо самостоятельно вносить изменения в код библиотеки.

```
if self.model_type in ['xgboost', 'catboost', 'lightboost']:
    if self.solo_model is False:
        # Обновляем параметры обучения
        self.main_fit_params.update({
            'X':X_train_new, 
            'y':y_train, 
            'eval_set':[(X_train_new, y_train), (X_val_new, y_val)]
            })
```

Поведение соответствует ожидаемому [в соотв. с документацией catboost](https://catboost.ai/en/docs/concepts/python-reference_catboostregressor_fit). 

Предлагаю добавить обработку этого кейса.

Спасибо.

**Comment by Vasily-Sizov** [comment]
Добрый день!
Спасибо за обратную связь. 

Добавили `model_type = 'catboost_gpu'.`
Также добавили небольшой пример под номер `6` в этом ноутбуке: https://github.com/Vasily-Sizov/autobinary_framework/blob/main/02_CV_importances_for_trees/2.1%20CV_bin_classification%20-%20different_models.ipynb
